# Generated by Django 3.1.8 on 2021-04-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('headline', models.CharField(max_length=255, unique=True)),
                ('thumbnail', models.SlugField(max_length=255)),
                ('source_of_news', models.CharField(max_length=50)),
                ('country_of_news', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
