# Generated by Django 3.1.8 on 2021-04-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210407_0811'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
