# Generated by Django 3.1.8 on 2021-04-07 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210407_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='source_of_news',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
