# Generated by Django 3.1.8 on 2021-04-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_news_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
